GET http://localhost:3000/api/firebase-validate
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkMWIxOWYwZjU4ZTJjOWE5Njc3M2M5MmNmODA0NDEwMTc5NzEzMjMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaGFjay10aGUtc2l4LWV4YW1wbGUiLCJhdWQiOiJoYWNrLXRoZS1zaXgtZXhhbXBsZSIsImF1dGhfdGltZSI6MTY2MDkxNTcyNywidXNlcl9pZCI6IklFNUE4WlRnVnFXR29IMmVxdVJUbXBGVHNnMDIiLCJzdWIiOiJJRTVBOFpUZ1ZxV0dvSDJlcXVSVG1wRlRzZzAyIiwiaWF0IjoxNjYwOTE1NzI3LCJleHAiOjE2NjA5MTkzMjcsImVtYWlsIjoidGVzdGluZ0BleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0aW5nQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.TMckFgBJbfVWnELAGdFYNlbraOpRc1lYJq1TQ8f0ZVCa2WpnnRjOIVqujhn1DhIFYXyPlCRKzRC577gqxOdnCLHl8d5NZwBU1Co3zz5aj9nlIQm6NQCcs8GBfdd1FC3143fiQ8QZBH_03hzN6FbYpIutN3onh0nApB-FqPjmQ6PQlP-XU9qLPuqBrkYEJkcLgdblgmiF0lVvyG2LdWgchckAY1kpZFJ32AvWdSxPE-iO4zHd1JGd6iKGLwnfvZev6o8_tURNcqL5HK8G4CQ_oq3r3KTJ1qq6nP3q6GoScYiZfEJYP7qvPOfB0C1XJW3oMz4gplYtYwbcH-42vdI6_A