import Head from 'next/head';
import { useRouter } from 'next/router';
export default function Home() {
  const router = useRouter();
  const gotoBlogs = () => router.push('/blog/first-blog');
  const gotoConfig = () => router.push('/config/user-field/type/name/John-Doe');
  const gotoNavigation = () => router.push('/navigation');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Full Stack Web Apps Using NEXT JS</h1>
        <button
          className='p-2 mt-2 ml-2 text-white bg-blue-600'
          onClick={gotoBlogs}>
          Blog: First Blog
        </button>
        <button
          className='p-2 mt-2 ml-2 text-white bg-blue-600'
          onClick={gotoConfig}>
          Config
        </button>
        <button
          className='p-2 mt-2 ml-2 text-white bg-blue-600'
          onClick={gotoNavigation}>
          Navigation
        </button>
      </main>
    </div>
  );
}
